const getRequestDataMutasiKeluar = (val) => {
  const {
    nama_pengusul,
    jenis_kelamin,
    tempat_tanggal_lahir,
    umur,
    kewarganegaraan,
    agama,
    status_perkawinan,
    pekerjaan,
    pendidikan_terakhir,
    alamat_asal,
    nik,
    tanggal_ktp,
    alamat_pindah,
    alasan_pindah,
    pengikut,
    catatan,
    foto_pengusul,
    nama_lengkap_keluarga,
    jenis_kelamin_keluarga,
    umur_keluarga,
    status_perkawinan_keluarga,
    pendidikan_terakhir_keluarga,
    nik_keluarga,
    keterangan,
  } = val;

  return {
    nama_pengusul,
    jenis_kelamin,
    tempat_tanggal_lahir,
    umur,
    kewarganegaraan,
    agama,
    status_perkawinan,
    pekerjaan,
    pendidikan_terakhir,
    alamat_asal,
    nik,
    tanggal_ktp,
    alamat_pindah,
    alasan_pindah,
    pengikut,
    catatan,
    foto_pengusul,
    nama_lengkap_keluarga,
    jenis_kelamin_keluarga,
    umur_keluarga,
    status_perkawinan_keluarga,
    pendidikan_terakhir_keluarga,
    nik_keluarga,
    keterangan,
  };
};

module.exports = getRequestDataMutasiKeluar;
